import nodemailer from 'nodemailer';

// Create email transporter
const createTransporter = () => {
  return nodemailer.createTransport({
    host: process.env.EMAIL_HOST || 'smtp.gmail.com',
    port: parseInt(process.env.EMAIL_PORT || '587'),
    secure: false, // true for 465, false for other ports
    auth: {
      user: process.env.EMAIL_USER,
      pass: process.env.EMAIL_PASSWORD,
    },
  });
};

// Email template for analysis report
const generateEmailHTML = (userName: string, score: number, analysisResult: string): string => {
  return `
<!DOCTYPE html>
<html>
<head>
  <style>
    body { font-family: Arial, sans-serif; line-height: 1.6; color: #333; }
    .container { max-width: 600px; margin: 0 auto; padding: 20px; }
    .header { background: linear-gradient(135deg, #667eea 0%, #764ba2 100%); color: white; padding: 30px; text-align: center; border-radius: 10px 10px 0 0; }
    .content { background: #f9fafb; padding: 30px; border-radius: 0 0 10px 10px; }
    .score-badge { display: inline-block; background: ${score >= 75 ? '#10b981' : score >= 60 ? '#f59e0b' : '#ef4444'}; color: white; padding: 15px 30px; border-radius: 50px; font-size: 24px; font-weight: bold; margin: 20px 0; }
    .section { background: white; padding: 20px; margin: 20px 0; border-radius: 8px; box-shadow: 0 2px 4px rgba(0,0,0,0.1); }
    .section h3 { color: #667eea; margin-top: 0; }
    .footer { text-align: center; margin-top: 30px; color: #6b7280; font-size: 12px; }
    pre { background: #1f2937; color: #e5e7eb; padding: 15px; border-radius: 6px; overflow-x: auto; }
  </style>
</head>
<body>
  <div class="container">
    <div class="header">
      <h1>🎯 ATS Resume Analysis Report</h1>
      <p>Generated by ATSPro AI</p>
    </div>
    <div class="content">
      <p>Hi ${userName},</p>
      <p>Your ATS resume analysis is complete! Here's your match score:</p>
      
      <div style="text-align: center;">
        <div class="score-badge">${score}%</div>
        <p><strong>${score >= 85 ? 'Excellent Match!' : score >= 75 ? 'Good Match' : score >= 65 ? 'Fair Match' : 'Needs Improvement'}</strong></p>
      </div>

      <div class="section">
        <h3>📊 Full Analysis Report</h3>
        <pre>${analysisResult.substring(0, 2000)}${analysisResult.length > 2000 ? '...\n\n[Full report available in your dashboard]' : ''}</pre>
      </div>

      <div class="section">
        <h3>💡 Next Steps</h3>
        <ul>
          <li>Review the recommended improvements</li>
          <li>Update your resume with missing keywords</li>
          <li>Re-run the analysis to track your progress</li>
          <li>Compare different versions in your dashboard</li>
        </ul>
      </div>

      <div style="text-align: center; margin-top: 30px;">
        <a href="${process.env.FRONTEND_URL}/score" style="display: inline-block; background: #667eea; color: white; padding: 12px 30px; text-decoration: none; border-radius: 6px; font-weight: bold;">View Full Report</a>
      </div>

      <div class="footer">
        <p>© 2026 ATS Resume Analyzer | <a href="${process.env.FRONTEND_URL}">Visit Dashboard</a></p>
        <p>This is an automated email. Please do not reply.</p>
      </div>
    </div>
  </div>
</body>
</html>
  `;
};

export const sendAnalysisEmail = async (
  toEmail: string,
  userName: string,
  score: number,
  analysisResult: string
): Promise<void> => {
  try {
    const transporter = createTransporter();

    const mailOptions = {
      from: process.env.EMAIL_FROM || '"ATS Analyzer" <noreply@atsanalyzer.com>',
      to: toEmail,
      subject: `🎯 Your ATS Score: ${score}% - Analysis Complete`,
      html: generateEmailHTML(userName, score, analysisResult),
      text: `Your ATS Analysis is complete!\n\nScore: ${score}%\n\n${analysisResult}`,
    };

    const info = await transporter.sendMail(mailOptions);
    console.log('✅ Email sent:', info.messageId);
  } catch (error) {
    console.error('❌ Email error:', error);
    throw new Error('Failed to send email');
  }
};
